# 対象ファイル

#Sample
# $FileName = "/Users/hiro/Program/C/Sample/Sample1/matricsA"
# $FileName = "/Users/hiro/Program/C/Sample/Sample1/matricsB"
# $FileName = "/Users/hiro/Program/C/Sample/Sample2/if-elseA"
# $FileName = "/Users/hiro/Program/C/Sample/Sample2/if-elseB"
# $FileName = "/Users/hiro/Program/C/Sample/Sample3/if-switchA"
# $FileName = "/Users/hiro/Program/C/Sample/Sample3/if-switchB"
# $FileName = "/Users/hiro/Program/C/Sample/Sample4/for-whileA"
# $FileName = "/Users/hiro/Program/C/Sample/Sample4/for-whileB"
# $FileName = "/Users/hiro/Program/C/Sample/Sample5/dowhile-whileA"
# $FileName = "/Users/hiro/Program/C/Sample/Sample5/dowhile-whileB"
# $FileName = "/Users/hiro/Program/C/Sample/Sample6/variableA"
# $FileName = "/Users/hiro/Program/C/Sample/Sample6/variableB"
# $FileName = "/Users/hiro/Program/C/Sample/Sample7/macroA"
# $FileName = "/Users/hiro/Program/C/Sample/Sample7/macroB"
# $FileName = "/Users/hiro/Program/C/Sample/Sample8/constantA"
# $FileName = "/Users/hiro/Program/C/Sample/Sample8/constantB"
$FileName = "/Users/hiro/Program/C/Sample/Sample9/loopA"
# $FileName = "/Users/hiro/Program/C/Sample/Sample10/cg"
# $FileName = "/Users/hiro/Program/Ruby/IR_Reader/Sample/sample"

# $FileName = "/Users/hiro/Program/C/common/if/A"
# $FileName = "/Users/hiro/Program/C/common/game/gomoku/game"
# $FileName = "/Users/hiro/Program/C/seminarl/C/BMP_Creater/create"
# $FileName = "/Users/hiro/Program/seminarl/C/BMP_Creater/create"
# $FileName = "/Users/hiro/Program/C/common/test/lisp"
